import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'da';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.inventory': 'Inventory',
    'nav.products': 'Products',
    'nav.import': 'Import',
    'nav.orders': 'Orders',
    'nav.reports': 'Reports',
    'nav.settings': 'Settings',
    
    // Common
    'common.search': 'Search',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.loading': 'Loading...',
    'common.all': 'All',
    'common.items': 'items',
    'common.products': 'products',
    'common.noResults': 'No results found',
    'common.tryAdjusting': 'Try adjusting your filters',
    'common.inactive': 'Inactive',
    'common.active': 'Active',
    
    // Auth
    'auth.signOut': 'Sign out',
    'auth.myAccount': 'My Account',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome back! Here\'s your inventory overview.',
    'dashboard.quickCount': 'Quick Count',
    'dashboard.addItem': 'Add Item',
    'dashboard.receive': 'Receive',
    'dashboard.categories': 'Categories',
    
    // Inventory
    'inventory.title': 'Inventory',
    'inventory.quickCount': 'Quick Count Mode',
    'inventory.manageStock': 'Manage your stock levels',
    'inventory.startCount': 'Start Count',
    'inventory.endSession': 'End Session',
    'inventory.confirmCount': 'Confirm Count',
    'inventory.lowStockOnly': 'low stock only',
    'inventory.items': 'items',
    'inventory.noProducts': 'No products found',
    'inventory.adjustFilters': 'Try adjusting your filters',
    'inventory.searchProducts': 'Search products...',
    'inventory.noLocations': 'No locations configured',
    'inventory.noStockLevel': 'No stock level',
    'inventory.openBottle': 'Open bottle level',
    'inventory.par': 'Par',
    'inventory.reorderAt': 'Reorder at',
    
    // Products
    'products.title': 'Products',
    'products.description': 'Manage your beverage catalog',
    'products.import': 'Import',
    'products.addProduct': 'Add Product',
    'products.searchPlaceholder': 'Search products or vendors...',
    'products.noProducts': 'No products found',
    'products.addFirst': 'Add your first product',
    'products.addNew': 'Add New Product',
    'products.productName': 'Product Name',
    'products.category': 'Category',
    'products.subtype': 'Subtype',
    'products.containerSize': 'Container Size',
    'products.unit': 'Unit',
    'products.vendor': 'Vendor (optional)',
    'products.duplicate': 'Duplicate',
    'products.archive': 'Archive',
    'products.restore': 'Restore',
    'products.productAdded': 'Product added',
    'products.productAddedDesc': 'has been added to the catalog.',
    'products.productDeleted': 'Product deleted',
    'products.productDeletedDesc': 'has been removed.',
    'products.productArchived': 'Product archived',
    'products.productRestored': 'Product restored',
    
    // Categories
    'category.all': 'All',
    'category.wine': 'Wine',
    'category.beer': 'Beer',
    'category.spirits': 'Spirits',
    'category.coffee': 'Coffee',
    'category.soda': 'Soda',
    'category.syrup': 'Syrup',
    
    // Orders
    'orders.title': 'Orders',
    'orders.description': 'Reorder suggestions & purchase orders',
    'orders.newOrder': 'New Order',
    'orders.suggested': 'Suggested',
    'orders.orders': 'Orders',
    'orders.history': 'History',
    'orders.suggestedOrders': 'Suggested Orders',
    'orders.createFromSuggestions': 'Create Order from Suggestions',
    'orders.current': 'Current',
    'orders.par': 'Par',
    'orders.suggested_lowercase': 'suggested',
    'orders.allStocked': 'All items are well stocked!',
    'orders.noSuggestions': 'No reorder suggestions at this time.',
    'orders.noActiveOrders': 'No active orders',
    'orders.createFirst': 'Create your first order',
    'orders.noHistory': 'No order history yet',
    'orders.completedOrders': 'Completed orders will appear here',
    
    // Reports
    'reports.title': 'Reports',
    'reports.description': 'Analytics and insights',
    'reports.variance': 'Variance',
    'reports.varianceDesc': 'POS vs actual inventory',
    'reports.usage': 'Usage',
    'reports.usageDesc': 'Consumption trends',
    'reports.cost': 'Cost',
    'reports.costDesc': 'COGS analysis',
    'reports.waste': 'Waste',
    'reports.wasteDesc': 'Breakage & wastage',
    'reports.varianceReport': 'Variance Report',
    'reports.vsPOS': 'vs POS sales',
    'reports.aiInsight': 'AI insight: Unusual variance compared to last 4 weeks average of',
    'reports.bottles': 'bottles',
    'reports.usageChart': 'Usage trends chart',
    'reports.connectCloud': 'Connect to Cloud for full analytics',
    'reports.costAnalysis': 'Cost analysis',
    'reports.wasteLog': 'Waste & breakage log',
    'reports.noWaste': 'No waste recorded in this period',
    'reports.days': 'Days',
    
    // Settings
    'settings.title': 'Settings',
    'settings.description': 'Configure your inventory system',
    'settings.locations': 'Locations',
    'settings.usersRoles': 'Users & Roles',
    'settings.spectraPOS': 'Spectra POS',
    'settings.notifications': 'Notifications',
    'settings.addLocation': 'Add Location',
    'settings.inviteUser': 'Invite User',
    'settings.rolePermissions': 'Role Permissions',
    'settings.adminDesc': 'Full access to all features',
    'settings.managerDesc': 'Inventory, orders, reports, cannot manage users',
    'settings.staffDesc': 'Quick count and receiving only',
    'settings.posIntegration': 'Spectra POS Integration',
    'settings.connectedTo': 'Connected to Spectra',
    'settings.posSystem': 'Spectra POS System',
    'settings.productMapping': 'Product Mapping',
    'settings.productMappingDesc': 'Map your POS items to inventory products for automatic stock updates.',
    'settings.configureMapping': 'Configure Mapping',
    'settings.servingSizes': 'Serving Sizes',
    'settings.servingSizesDesc': 'Set standard pour sizes for accurate depletion tracking.',
    'settings.wineGlass': 'Wine (glass)',
    'settings.spiritShot': 'Spirit (shot)',
    'settings.beerPint': 'Beer (pint)',
    'settings.lowStockAlerts': 'Low Stock Alerts',
    'settings.lowStockAlertsDesc': 'Get notified when items hit reorder threshold',
    'settings.varianceAlerts': 'Variance Alerts',
    'settings.varianceAlertsDesc': 'Notify when variance exceeds 10%',
    'settings.orderReminders': 'Order Reminders',
    'settings.orderRemindersDesc': 'Weekly reminder to review suggested orders',
    'settings.countReminders': 'Count Reminders',
    'settings.countRemindersDesc': 'Remind to count inventory weekly',
    'settings.tablePlan': 'Table Plan',
    'settings.autoSave': 'Auto-save table plans',
    'settings.autoSaveDesc': 'Automatically save table plans as you make changes',
    
    // Import
    'import.title': 'Import Products',
    'import.description': 'Upload an Excel or CSV file to import products',
    'import.uploadFile': 'Upload File',
    'import.uploadDesc': 'Upload an Excel (.xlsx) or CSV file with your product data',
    'import.clickUpload': 'Click to upload or drag and drop',
    'import.fileTypes': 'XLSX, XLS, or CSV',
    'import.downloadTemplate': 'Download Template',
    'import.importStatus': 'Import Status',
    'import.reviewImport': 'Review and import your products',
    'import.validProducts': 'Valid products',
    'import.withErrors': 'With errors',
    'import.importing': 'Importing...',
    'import.importComplete': 'Import Complete',
    'import.imported': 'imported',
    'import.failed': 'failed',
    'import.importProducts': 'Import Products',
    'import.uploadPreview': 'Upload a file to preview products',
    'import.dataPreview': 'Data Preview',
    'import.reviewBefore': 'Review your products before importing',
    'import.expectedColumns': 'Expected Columns',
    'import.expectedColumnsDesc': 'Your file should include these columns (case-insensitive)',
    'import.required': 'required',
    'import.productName': 'Product name',
    
    // Table Plan
    'nav.tablePlan': 'Table Plan',
    'tablePlan.title': 'Table Plan',
    'tablePlan.subtitle': 'Upload today\'s Køkkenliste to see tonight\'s seating',
    'tablePlan.uploadPdf': 'Upload Køkkenliste PDF',
    'tablePlan.dragDrop': 'Drag and drop or click to browse',
    'tablePlan.processing': 'Processing PDF...',
    'tablePlan.extracting': 'Extracting reservations from 18:00 onwards',
    'tablePlan.free': 'Free',
    'tablePlan.guests': 'guests',
    'tablePlan.room': 'Room',
    'tablePlan.tablesOccupied': 'tables occupied',
    'tablePlan.noReservations': 'No restaurant reservations found for tonight',
    'tablePlan.newUpload': 'New Upload',
    'tablePlan.extracted': 'Reservations extracted',
    'tablePlan.reservationsFound': 'reservations found',
    'tablePlan.error': 'Error',
    'tablePlan.errorDesc': 'Could not extract reservations from the PDF. Please try again.',
    'tablePlan.addReservation': 'Add Reservation',
    'tablePlan.table': 'Table',
    'tablePlan.guestName': 'Guest Name',
    'tablePlan.guestCount': 'Guest Count',
    'tablePlan.roomNumber': 'Room Number',
    'tablePlan.type': 'Type',
    'tablePlan.notes': 'Notes',
    'tablePlan.remove': 'Remove',
    'tablePlan.merge': 'Merge tables',
    'tablePlan.unmerge': 'Unmerge',
    'tablePlan.markAsBuff': 'Mark as BUFF',
    'tablePlan.markAsUnavailable': 'Mark as unavailable',
    'tablePlan.tableUnavailableMessage': 'This table was marked as unavailable',
    'tablePlan.makeAvailable': 'Make available',
    'tablePlan.buff': 'BUFF',
    'tablePlan.arrived': 'Arrived',
    'tablePlan.clearTable': 'Clear',
    'tablePlan.clearAll': 'Clear All',
    'tablePlan.clearAllConfirm': 'Are you sure you want to clear all tables? This will remove all reservations from the floor plan.',
    'tablePlan.saving': 'Saving...',
    'tablePlan.saved': 'Saved',
    'tablePlan.savedPlans': 'Saved Plans',
    'tablePlan.loadPlan': 'Load Plan',
    'tablePlan.deletePlan': 'Delete Plan',

    // Preparation Summary
    'prep.title': 'Preparation Summary',
    'prep.cutlery': 'Cutlery',
    'prep.glassware': 'Glassware',
    'prep.forks': 'Forks',
    'prep.steakKnives': 'Steak knives',
    'prep.butterKnives': 'Butter knives',
    'prep.spoons': 'Spoons',
    'prep.waterGlass': 'Water glasses',
    'prep.whiteWine': 'White wine glasses',
    'prep.redWine': 'Red wine glasses',
    'prep.coffeeTea': 'Coffee/tea + sweet',
    'prep.coffeeOnly': 'Coffee/tea',
    'tablePlan.print': 'Print',
    'tablePlan.printEmpty': 'Print empty plan',
    'tablePlan.printWithRes': 'Print with reservations',

    // Language
    'language.english': 'English',
    'language.danish': 'Dansk',

    // User Management
    'nav.userManagement': 'User Management',
    'users.title': 'User Management',
    'users.description': 'Manage staff accounts, roles, and permissions',
    'users.addUser': 'Add User',
    'users.editUser': 'Edit User',
    'users.fullName': 'Full Name',
    'users.email': 'Email',
    'users.phone': 'Phone',
    'users.role': 'Role',
    'users.status': 'Status',
    'users.actions': 'Actions',
    'users.approved': 'Approved',
    'users.pending': 'Pending',
    'users.tempPassword': 'Temporary Password',
    'users.resetPassword': 'Reset Password',
    'users.confirmDelete': 'Delete User',
    'users.confirmDeleteDesc': 'Are you sure you want to permanently delete',
    'users.resetLinkGenerated': 'Password Reset Link',
    'users.copyLink': 'Copy Link',
    'users.departments': 'Departments',

    // Departments
    'dept.reception': 'Reception',
    'dept.housekeeping': 'Housekeeping',
    'dept.restaurant': 'Restaurant',

    // Reception & Housekeeping nav
    'nav.reception': 'Reception',
    'nav.housekeeping': 'Housekeeping',
    'nav.restaurant': 'Restaurant',
    'nav.departments': 'Departments',
    'nav.hotelOps': 'Hotel Operations',

    // Reception
    'reception.title': 'Reception',
    'reception.subtitle': 'Room management and guest operations',
    'reception.roomBoard': 'Room Board',
    'reception.today': 'Today',
    'reception.guestDirectory': 'Guest Directory',
    'reception.available': 'Available',
    'reception.occupied': 'Occupied',
    'reception.checkout': 'Checkout',
    'reception.maintenance': 'Maintenance',
    'reception.reserved': 'Reserved',
    'reception.allStatuses': 'All statuses',
    'reception.allFloors': 'All floors',
    'reception.floor': 'Floor',
    'reception.room': 'Room',
    'reception.noRooms': 'No rooms found',
    'reception.checkIn': 'Check In',
    'reception.checkOut': 'Check Out',
    'reception.arrivals': 'Arrivals',
    'reception.departures': 'Departures',
    'reception.noArrivals': 'No arrivals today',
    'reception.noDepartures': 'No departures today',
    'reception.guests': 'guests',
    'reception.adults': 'adults',
    'reception.children': 'children',
    'reception.noReservation': 'No reservation found for this room',
    'reception.charges': 'Outstanding Charges',
    'reception.total': 'Total',
    'reception.paymentStatus': 'Payment',
    'reception.searchGuests': 'Search guests...',
    'reception.addGuest': 'Add Guest',
    'reception.guestName': 'Name',
    'reception.firstName': 'First Name',
    'reception.lastName': 'Last Name',
    'reception.nationality': 'Nationality',
    'reception.visits': 'Visits',

    // Housekeeping
    'housekeeping.title': 'Housekeeping',
    'housekeeping.subtitle': 'Room cleaning and maintenance',
    'housekeeping.statusBoard': 'Status Board',
    'housekeeping.myTasks': 'My Tasks',
    'housekeeping.dirty': 'Dirty',
    'housekeeping.inProgress': 'In Progress',
    'housekeeping.clean': 'Clean',
    'housekeeping.inspected': 'Inspected',
    'housekeeping.startCleaning': 'Start',
    'housekeeping.markClean': 'Done',
    'housekeeping.markInspected': 'Inspect',
    'housekeeping.generateTasks': 'Generate Tasks',
    'housekeeping.noTasks': 'No tasks for today',
    'housekeeping.noAssignedTasks': 'No tasks assigned to you',
    'housekeeping.taskType.checkout_clean': 'Checkout Clean',
    'housekeeping.taskType.stay_over': 'Stay Over',
    'housekeeping.taskType.deep_clean': 'Deep Clean',
    'housekeeping.taskType.turndown': 'Turndown',
    'housekeeping.addNote': 'Add note',
    'housekeeping.managerNote': 'Manager note',

    // Reception notes
    'reception.addNote': 'Add note',
    'reception.notes': 'Notes',
    'reception.roomType.single': 'Single',
    'reception.roomType.double': 'Double',
    'reception.roomType.twin': 'Twin',
    'reception.roomType.suite': 'Suite',
    'reception.roomType.family': 'Family',
  },
  da: {
    // Navigation
    'nav.dashboard': 'Oversigt',
    'nav.inventory': 'Lager',
    'nav.products': 'Produkter',
    'nav.import': 'Importer',
    'nav.orders': 'Ordrer',
    'nav.reports': 'Rapporter',
    'nav.settings': 'Indstillinger',
    
    // Common
    'common.search': 'Søg',
    'common.save': 'Gem',
    'common.cancel': 'Annuller',
    'common.confirm': 'Bekræft',
    'common.delete': 'Slet',
    'common.edit': 'Rediger',
    'common.add': 'Tilføj',
    'common.loading': 'Indlæser...',
    'common.all': 'Alle',
    'common.items': 'varer',
    'common.products': 'produkter',
    'common.noResults': 'Ingen resultater fundet',
    'common.tryAdjusting': 'Prøv at justere dine filtre',
    'common.inactive': 'Inaktiv',
    'common.active': 'Aktiv',
    
    // Auth
    'auth.signOut': 'Log ud',
    'auth.myAccount': 'Min konto',
    
    // Dashboard
    'dashboard.title': 'Oversigt',
    'dashboard.welcome': 'Velkommen tilbage! Her er dit lageroversigt.',
    'dashboard.quickCount': 'Hurtig optælling',
    'dashboard.addItem': 'Tilføj vare',
    'dashboard.receive': 'Modtag',
    'dashboard.categories': 'Kategorier',
    
    // Inventory
    'inventory.title': 'Lager',
    'inventory.quickCount': 'Hurtig optællingstilstand',
    'inventory.manageStock': 'Administrer dine lagerniveauer',
    'inventory.startCount': 'Start optælling',
    'inventory.endSession': 'Afslut session',
    'inventory.confirmCount': 'Bekræft optælling',
    'inventory.lowStockOnly': 'kun lav beholdning',
    'inventory.items': 'varer',
    'inventory.noProducts': 'Ingen produkter fundet',
    'inventory.adjustFilters': 'Prøv at justere dine filtre',
    'inventory.searchProducts': 'Søg produkter...',
    'inventory.noLocations': 'Ingen lokationer konfigureret',
    'inventory.noStockLevel': 'Intet lagerniveau',
    'inventory.openBottle': 'Åben flaskeniveau',
    'inventory.par': 'Par',
    'inventory.reorderAt': 'Genbestil ved',
    
    // Products
    'products.title': 'Produkter',
    'products.description': 'Administrer dit drikkevare katalog',
    'products.import': 'Importer',
    'products.addProduct': 'Tilføj produkt',
    'products.searchPlaceholder': 'Søg produkter eller leverandører...',
    'products.noProducts': 'Ingen produkter fundet',
    'products.addFirst': 'Tilføj dit første produkt',
    'products.addNew': 'Tilføj nyt produkt',
    'products.productName': 'Produktnavn',
    'products.category': 'Kategori',
    'products.subtype': 'Undertype',
    'products.containerSize': 'Beholder størrelse',
    'products.unit': 'Enhed',
    'products.vendor': 'Leverandør (valgfri)',
    'products.duplicate': 'Duplikér',
    'products.archive': 'Arkiver',
    'products.restore': 'Gendan',
    'products.productAdded': 'Produkt tilføjet',
    'products.productAddedDesc': 'er blevet tilføjet til kataloget.',
    'products.productDeleted': 'Produkt slettet',
    'products.productDeletedDesc': 'er blevet fjernet.',
    'products.productArchived': 'Produkt arkiveret',
    'products.productRestored': 'Produkt genoprettet',
    
    // Categories
    'category.all': 'Alle',
    'category.wine': 'Vin',
    'category.beer': 'Øl',
    'category.spirits': 'Spiritus',
    'category.coffee': 'Kaffe',
    'category.soda': 'Sodavand',
    'category.syrup': 'Sirup',
    
    // Orders
    'orders.title': 'Ordrer',
    'orders.description': 'Genbestillingsforslag & indkøbsordrer',
    'orders.newOrder': 'Ny ordre',
    'orders.suggested': 'Foreslået',
    'orders.orders': 'Ordrer',
    'orders.history': 'Historik',
    'orders.suggestedOrders': 'Foreslåede ordrer',
    'orders.createFromSuggestions': 'Opret ordre fra forslag',
    'orders.current': 'Nuværende',
    'orders.par': 'Par',
    'orders.suggested_lowercase': 'foreslået',
    'orders.allStocked': 'Alle varer er godt på lager!',
    'orders.noSuggestions': 'Ingen genbestillingsforslag på nuværende tidspunkt.',
    'orders.noActiveOrders': 'Ingen aktive ordrer',
    'orders.createFirst': 'Opret din første ordre',
    'orders.noHistory': 'Ingen ordrehistorik endnu',
    'orders.completedOrders': 'Afsluttede ordrer vises her',
    
    // Reports
    'reports.title': 'Rapporter',
    'reports.description': 'Analyser og indsigt',
    'reports.variance': 'Afvigelse',
    'reports.varianceDesc': 'POS vs faktisk lager',
    'reports.usage': 'Forbrug',
    'reports.usageDesc': 'Forbrugstendenser',
    'reports.cost': 'Omkostninger',
    'reports.costDesc': 'COGS analyse',
    'reports.waste': 'Spild',
    'reports.wasteDesc': 'Brud & spild',
    'reports.varianceReport': 'Afvigelsesrapport',
    'reports.vsPOS': 'vs POS salg',
    'reports.aiInsight': 'AI indsigt: Usædvanlig afvigelse sammenlignet med de sidste 4 ugers gennemsnit på',
    'reports.bottles': 'flasker',
    'reports.usageChart': 'Forbrugstendens graf',
    'reports.connectCloud': 'Forbind til Cloud for fuld analyse',
    'reports.costAnalysis': 'Omkostningsanalyse',
    'reports.wasteLog': 'Spild & brud log',
    'reports.noWaste': 'Ingen spild registreret i denne periode',
    'reports.days': 'Dage',
    
    // Settings
    'settings.title': 'Indstillinger',
    'settings.description': 'Konfigurer dit lagersystem',
    'settings.locations': 'Lokationer',
    'settings.usersRoles': 'Brugere & roller',
    'settings.spectraPOS': 'Spectra POS',
    'settings.notifications': 'Notifikationer',
    'settings.addLocation': 'Tilføj lokation',
    'settings.inviteUser': 'Inviter bruger',
    'settings.rolePermissions': 'Rolletilladelser',
    'settings.adminDesc': 'Fuld adgang til alle funktioner',
    'settings.managerDesc': 'Lager, ordrer, rapporter, kan ikke administrere brugere',
    'settings.staffDesc': 'Kun hurtig optælling og modtagelse',
    'settings.posIntegration': 'Spectra POS Integration',
    'settings.connectedTo': 'Forbundet til Spectra',
    'settings.posSystem': 'Spectra POS System',
    'settings.productMapping': 'Produktkortlægning',
    'settings.productMappingDesc': 'Kortlæg dine POS varer til lagerprodukter for automatiske lageropdateringer.',
    'settings.configureMapping': 'Konfigurer kortlægning',
    'settings.servingSizes': 'Portionsstørrelser',
    'settings.servingSizesDesc': 'Indstil standard skænkestørrelser for præcis opfølgning.',
    'settings.wineGlass': 'Vin (glas)',
    'settings.spiritShot': 'Spiritus (shot)',
    'settings.beerPint': 'Øl (pint)',
    'settings.lowStockAlerts': 'Lav lager advarsler',
    'settings.lowStockAlertsDesc': 'Få besked når varer rammer genbestillingsgrænsen',
    'settings.varianceAlerts': 'Afvigelsesadvarsler',
    'settings.varianceAlertsDesc': 'Giv besked når afvigelse overstiger 10%',
    'settings.orderReminders': 'Ordrepåmindelser',
    'settings.orderRemindersDesc': 'Ugentlig påmindelse om at gennemgå foreslåede ordrer',
    'settings.countReminders': 'Optællingspåmindelser',
    'settings.countRemindersDesc': 'Påmind om at tælle lager ugentligt',
    'settings.tablePlan': 'Bordplan',
    'settings.autoSave': 'Auto-gem bordplaner',
    'settings.autoSaveDesc': 'Gem automatisk bordplaner når du foretager ændringer',
    
    // Import
    'import.title': 'Importer produkter',
    'import.description': 'Upload en Excel eller CSV fil for at importere produkter',
    'import.uploadFile': 'Upload fil',
    'import.uploadDesc': 'Upload en Excel (.xlsx) eller CSV fil med dine produktdata',
    'import.clickUpload': 'Klik for at uploade eller træk og slip',
    'import.fileTypes': 'XLSX, XLS eller CSV',
    'import.downloadTemplate': 'Download skabelon',
    'import.importStatus': 'Importstatus',
    'import.reviewImport': 'Gennemse og importer dine produkter',
    'import.validProducts': 'Gyldige produkter',
    'import.withErrors': 'Med fejl',
    'import.importing': 'Importerer...',
    'import.importComplete': 'Import fuldført',
    'import.imported': 'importeret',
    'import.failed': 'fejlet',
    'import.importProducts': 'Importer produkter',
    'import.uploadPreview': 'Upload en fil for at forhåndsvise produkter',
    'import.dataPreview': 'Data forhåndsvisning',
    'import.reviewBefore': 'Gennemse dine produkter før import',
    'import.expectedColumns': 'Forventede kolonner',
    'import.expectedColumnsDesc': 'Din fil skal indeholde disse kolonner (ikke versalfølsom)',
    'import.required': 'påkrævet',
    'import.productName': 'Produktnavn',
    
    // Table Plan
    'nav.tablePlan': 'Bordplan',
    'tablePlan.title': 'Bordplan',
    'tablePlan.subtitle': 'Upload dagens køkkenliste for at se aftenens bordplan',
    'tablePlan.uploadPdf': 'Upload køkkenliste PDF',
    'tablePlan.dragDrop': 'Træk og slip eller klik for at vælge',
    'tablePlan.processing': 'Behandler PDF...',
    'tablePlan.extracting': 'Udtrækker reservationer fra kl. 18:00',
    'tablePlan.free': 'Fri',
    'tablePlan.guests': 'gæster',
    'tablePlan.room': 'Værelse',
    'tablePlan.tablesOccupied': 'borde optaget',
    'tablePlan.noReservations': 'Ingen restaurantreservationer fundet for i aften',
    'tablePlan.newUpload': 'Ny upload',
    'tablePlan.extracted': 'Reservationer udtrukket',
    'tablePlan.reservationsFound': 'reservationer fundet',
    'tablePlan.error': 'Fejl',
    'tablePlan.errorDesc': 'Kunne ikke udtrække reservationer fra PDF. Prøv igen.',
    'tablePlan.addReservation': 'Tilføj reservation',
    'tablePlan.table': 'Bord',
    'tablePlan.guestName': 'Gæstenavn',
    'tablePlan.guestCount': 'Antal gæster',
    'tablePlan.roomNumber': 'Værelsesnummer',
    'tablePlan.type': 'Type',
    'tablePlan.notes': 'Bemærkninger',
    'tablePlan.remove': 'Fjern',
    'tablePlan.merge': 'Sammenlæg borde',
    'tablePlan.unmerge': 'Opdel',
    'tablePlan.markAsBuff': 'Markér som BUFF',
    'tablePlan.markAsUnavailable': 'Markér som utilgængelig',
    'tablePlan.tableUnavailableMessage': 'Dette bord er markeret som utilgængeligt',
    'tablePlan.makeAvailable': 'Gør tilgængelig',
    'tablePlan.buff': 'BUFF',
    'tablePlan.arrived': 'Ankommet',
    'tablePlan.clearTable': 'Ryd',
    'tablePlan.clearAll': 'Ryd alle',
    'tablePlan.clearAllConfirm': 'Er du sikker på at du vil rydde alle borde? Dette fjerner alle reservationer fra bordplanen.',
    'tablePlan.saving': 'Gemmer...',
    'tablePlan.saved': 'Gemt',
    'tablePlan.savedPlans': 'Gemte planer',
    'tablePlan.loadPlan': 'Indlæs plan',
    'tablePlan.deletePlan': 'Slet plan',

    // Preparation Summary
    'prep.title': 'Forberedelsesopsummering',
    'prep.cutlery': 'Bestik',
    'prep.glassware': 'Glas',
    'prep.forks': 'Gafler',
    'prep.steakKnives': 'Steakknive',
    'prep.butterKnives': 'Smørknive',
    'prep.spoons': 'Skeer',
    'prep.waterGlass': 'Vandglas',
    'prep.whiteWine': 'Hvidvinsglas',
    'prep.redWine': 'Rødvinsglas',
    'prep.coffeeTea': 'Kaffe/te + sødt',
    'prep.coffeeOnly': 'Kaffe/te',
    'tablePlan.print': 'Udskriv',
    'tablePlan.printEmpty': 'Udskriv tom plan',
    'tablePlan.printWithRes': 'Udskriv med reservationer',

    // Language
    'language.english': 'English',
    'language.danish': 'Dansk',

    // User Management
    'nav.userManagement': 'Brugeradministration',
    'users.title': 'Brugeradministration',
    'users.description': 'Administrer medarbejderkonti, roller og tilladelser',
    'users.addUser': 'Tilføj bruger',
    'users.editUser': 'Rediger bruger',
    'users.fullName': 'Fulde navn',
    'users.email': 'Email',
    'users.phone': 'Telefon',
    'users.role': 'Rolle',
    'users.status': 'Status',
    'users.actions': 'Handlinger',
    'users.approved': 'Godkendt',
    'users.pending': 'Afventer',
    'users.tempPassword': 'Midlertidigt kodeord',
    'users.resetPassword': 'Nulstil kodeord',
    'users.confirmDelete': 'Slet bruger',
    'users.confirmDeleteDesc': 'Er du sikker på at du vil slette permanent',
    'users.resetLinkGenerated': 'Nulstil kodeord link',
    'users.copyLink': 'Kopier link',
    'users.departments': 'Afdelinger',

    // Departments
    'dept.reception': 'Reception',
    'dept.housekeeping': 'Housekeeping',
    'dept.restaurant': 'Restaurant',

    // Reception & Housekeeping nav
    'nav.reception': 'Reception',
    'nav.housekeeping': 'Rengøring',
    'nav.restaurant': 'Restaurant',
    'nav.departments': 'Afdelinger',
    'nav.hotelOps': 'Hoteldrift',

    // Reception
    'reception.title': 'Reception',
    'reception.subtitle': 'Værelseadministration og gæsteoperationer',
    'reception.roomBoard': 'Værelseoversigt',
    'reception.today': 'I dag',
    'reception.guestDirectory': 'Gæsteregister',
    'reception.available': 'Ledig',
    'reception.occupied': 'Optaget',
    'reception.checkout': 'Checkout',
    'reception.maintenance': 'Vedligeholdelse',
    'reception.reserved': 'Reserveret',
    'reception.allStatuses': 'Alle statusser',
    'reception.allFloors': 'Alle etager',
    'reception.floor': 'Etage',
    'reception.room': 'Værelse',
    'reception.noRooms': 'Ingen værelser fundet',
    'reception.checkIn': 'Check ind',
    'reception.checkOut': 'Check ud',
    'reception.arrivals': 'Ankomster',
    'reception.departures': 'Afrejser',
    'reception.noArrivals': 'Ingen ankomster i dag',
    'reception.noDepartures': 'Ingen afrejser i dag',
    'reception.guests': 'gæster',
    'reception.adults': 'voksne',
    'reception.children': 'børn',
    'reception.noReservation': 'Ingen reservation fundet for dette værelse',
    'reception.charges': 'Udestående gebyrer',
    'reception.total': 'Total',
    'reception.paymentStatus': 'Betaling',
    'reception.searchGuests': 'Søg gæster...',
    'reception.addGuest': 'Tilføj gæst',
    'reception.guestName': 'Navn',
    'reception.firstName': 'Fornavn',
    'reception.lastName': 'Efternavn',
    'reception.nationality': 'Nationalitet',
    'reception.visits': 'Besøg',

    // Housekeeping
    'housekeeping.title': 'Housekeeping',
    'housekeeping.subtitle': 'Rengøring og vedligeholdelse',
    'housekeeping.statusBoard': 'Statusoversigt',
    'housekeeping.myTasks': 'Mine opgaver',
    'housekeeping.dirty': 'Beskidt',
    'housekeeping.inProgress': 'I gang',
    'housekeeping.clean': 'Ren',
    'housekeeping.inspected': 'Inspiceret',
    'housekeeping.startCleaning': 'Start',
    'housekeeping.markClean': 'Færdig',
    'housekeeping.markInspected': 'Inspicér',
    'housekeeping.generateTasks': 'Generer opgaver',
    'housekeeping.noTasks': 'Ingen opgaver i dag',
    'housekeeping.noAssignedTasks': 'Ingen opgaver tildelt dig',
    'housekeeping.taskType.checkout_clean': 'Checkout rengøring',
    'housekeeping.taskType.stay_over': 'Stay over',
    'housekeeping.taskType.deep_clean': 'Grundig rengøring',
    'housekeeping.taskType.turndown': 'Turndown',
    'housekeeping.addNote': 'Tilføj note',
    'housekeeping.managerNote': 'Ledernote',

    // Reception notes
    'reception.addNote': 'Tilføj note',
    'reception.notes': 'Noter',
    'reception.roomType.single': 'Enkelt',
    'reception.roomType.double': 'Dobbelt',
    'reception.roomType.twin': 'Twin',
    'reception.roomType.suite': 'Suite',
    'reception.roomType.family': 'Familie',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('pourstock-language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('pourstock-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
