import { useState } from 'react';
import { useReservations, useRooms } from '@/hooks/useReception';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import {
  FileText, Printer, Download, Users, LogOut, ArrowDownToLine, BarChart3, ClipboardList,
} from 'lucide-react';
import { format, addDays } from 'date-fns';

function currencyDKK(amount: number) {
  return new Intl.NumberFormat('da-DK', { style: 'currency', currency: 'DKK', maximumFractionDigits: 0 }).format(amount);
}

// ── Print helpers ─────────────────────────────────────────────────────────────

function printHTML(title: string, body: string) {
  const w = window.open('', '_blank');
  if (!w) return;
  w.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title}</title>
      <meta charset="utf-8" />
      <style>
        body { font-family: Arial, sans-serif; font-size: 13px; color: #111; margin: 32px; }
        h1 { font-size: 20px; margin-bottom: 4px; }
        h2 { font-size: 15px; margin: 20px 0 6px; border-bottom: 1px solid #ccc; padding-bottom: 4px; }
        table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        th, td { text-align: left; padding: 6px 10px; border-bottom: 1px solid #e5e5e5; }
        th { background: #f3f4f6; font-weight: 600; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 11px; font-weight: 500; }
        .green { background: #d1fae5; color: #065f46; }
        .amber { background: #fef3c7; color: #92400e; }
        .footer { margin-top: 40px; font-size: 11px; color: #999; border-top: 1px solid #e5e5e5; padding-top: 8px; }
        @media print { button { display: none; } }
      </style>
    </head>
    <body>
      ${body}
      <div class="footer">Generated by PourStock · ${format(new Date(), 'PPpp')}</div>
      <script>window.onload = () => window.print();</script>
    </body>
    </html>
  `);
  w.document.close();
}

// ── Document definitions ──────────────────────────────────────────────────────

const DOC_CATEGORIES = [
  {
    label: 'Guest Documents',
    icon: Users,
    docs: [
      {
        id: 'arrivals-manifest',
        title: 'Daily Arrivals Manifest',
        desc: 'Print-ready list of all arrivals for today.',
        icon: ArrowDownToLine,
      },
      {
        id: 'departure-checklist',
        title: 'Departure Checklist',
        desc: "Today's departures with room and balance status.",
        icon: LogOut,
      },
    ],
  },
  {
    label: 'Hotel Operational Documents',
    icon: ClipboardList,
    docs: [
      {
        id: 'eod-revenue',
        title: 'End-of-Day Revenue Summary',
        desc: 'Total revenue, payments, and outstanding balances.',
        icon: BarChart3,
      },
      {
        id: 'occupancy-report',
        title: 'Occupancy Report',
        desc: 'Room-by-room status and current occupancy rate.',
        icon: FileText,
      },
    ],
  },
];

// ── Main component ────────────────────────────────────────────────────────────

export function DocumentCentre() {
  const today = new Date().toISOString().split('T')[0];
  const { data: reservations = [] } = useReservations({ from: today, to: today });
  const { data: rooms = [] } = useRooms();

  function generateDocument(id: string) {
    const todayLabel = format(new Date(), 'PPP');

    if (id === 'arrivals-manifest') {
      const arrivals = (reservations as any[]).filter((r) => r.check_in_date === today);
      const rows = arrivals.map((r: any) => `
        <tr>
          <td>${r.guest?.first_name ?? ''} ${r.guest?.last_name ?? ''}</td>
          <td>${r.room?.room_number ?? '—'}</td>
          <td>${r.check_out_date}</td>
          <td>${r.adults} adult${r.adults !== 1 ? 's' : ''}${r.children > 0 ? ` + ${r.children} child` : ''}</td>
          <td><span class="badge ${r.status === 'checked_in' ? 'green' : 'amber'}">${r.status}</span></td>
          <td>${r.special_requests ?? ''}</td>
        </tr>
      `).join('');
      printHTML('Daily Arrivals Manifest', `
        <h1>Daily Arrivals Manifest</h1>
        <p style="color:#666">${todayLabel} · ${arrivals.length} arrival${arrivals.length !== 1 ? 's' : ''}</p>
        <table>
          <thead><tr><th>Guest</th><th>Room</th><th>Checkout</th><th>Pax</th><th>Status</th><th>Notes</th></tr></thead>
          <tbody>${rows || '<tr><td colspan="6" style="text-align:center;color:#999">No arrivals today</td></tr>'}</tbody>
        </table>
      `);
    }

    if (id === 'departure-checklist') {
      const departures = (reservations as any[]).filter((r) => r.check_out_date === today);
      const rows = departures.map((r: any) => `
        <tr>
          <td>${r.guest?.first_name ?? ''} ${r.guest?.last_name ?? ''}</td>
          <td>${r.room?.room_number ?? '—'}</td>
          <td>${r.check_in_date}</td>
          <td><span class="badge ${r.payment_status === 'paid' ? 'green' : 'amber'}">${r.payment_status}</span></td>
          <td style="text-align:center">☐</td>
          <td style="text-align:center">☐</td>
        </tr>
      `).join('');
      printHTML('Departure Checklist', `
        <h1>Departure Checklist</h1>
        <p style="color:#666">${todayLabel} · ${departures.length} departure${departures.length !== 1 ? 's' : ''}</p>
        <table>
          <thead><tr><th>Guest</th><th>Room</th><th>Arrived</th><th>Balance</th><th>Key returned</th><th>Invoice sent</th></tr></thead>
          <tbody>${rows || '<tr><td colspan="6" style="text-align:center;color:#999">No departures today</td></tr>'}</tbody>
        </table>
      `);
    }

    if (id === 'eod-revenue') {
      const checkedIn = (reservations as any[]).filter((r) => r.status === 'checked_in');
      const total = checkedIn.reduce((s: number, r: any) => s + (r.total_amount ?? 0), 0);
      const paid = checkedIn.filter((r: any) => r.payment_status === 'paid').length;
      const pending = checkedIn.filter((r: any) => r.payment_status !== 'paid').length;
      printHTML('End-of-Day Revenue Summary', `
        <h1>End-of-Day Revenue Summary</h1>
        <p style="color:#666">${todayLabel}</p>
        <table>
          <thead><tr><th>Metric</th><th>Value</th></tr></thead>
          <tbody>
            <tr><td>Guests checked in</td><td>${checkedIn.length}</td></tr>
            <tr><td>Total reservation value</td><td>${currencyDKK(total)}</td></tr>
            <tr><td>Accounts settled (paid)</td><td>${paid}</td></tr>
            <tr><td>Accounts pending</td><td>${pending}</td></tr>
          </tbody>
        </table>
      `);
    }

    if (id === 'occupancy-report') {
      const roomList = rooms as any[];
      const statusColor: Record<string, string> = {
        available: 'green', occupied: 'amber', checkout: 'amber',
      };
      const rows = roomList.map((r: any) => `
        <tr>
          <td>${r.room_number}</td>
          <td>${r.room_type}</td>
          <td>Floor ${r.floor}</td>
          <td><span class="badge ${statusColor[r.status] ?? ''}">${r.status}</span></td>
        </tr>
      `).join('');
      const occupied = roomList.filter((r) => r.status === 'occupied').length;
      printHTML('Occupancy Report', `
        <h1>Occupancy Report</h1>
        <p style="color:#666">${todayLabel} · ${occupied}/${roomList.length} rooms occupied (${roomList.length > 0 ? Math.round(occupied/roomList.length*100) : 0}%)</p>
        <table>
          <thead><tr><th>Room</th><th>Type</th><th>Floor</th><th>Status</th></tr></thead>
          <tbody>${rows}</tbody>
        </table>
      `);
    }
  }

  return (
    <div className="space-y-6">
      <p className="text-sm text-muted-foreground">
        Generate and print operational documents for front-desk use.
      </p>

      {DOC_CATEGORIES.map(({ label, icon: CatIcon, docs }) => (
        <div key={label}>
          <h2 className="text-sm font-semibold text-muted-foreground uppercase tracking-wide mb-3 flex items-center gap-2">
            <CatIcon className="h-4 w-4" /> {label}
          </h2>
          <div className="grid sm:grid-cols-2 gap-3">
            {docs.map(({ id, title, desc, icon: Icon }) => (
              <Card key={id} className="glass-card border-border/50 hover:border-primary/30 transition-colors">
                <CardContent className="pt-4 pb-4">
                  <div className="flex items-start gap-3">
                    <div className="w-9 h-9 rounded-lg bg-primary/10 flex items-center justify-center flex-shrink-0">
                      <Icon className="h-4 w-4 text-primary" />
                    </div>
                    <div className="flex-1 min-w-0">
                      <p className="font-medium text-sm">{title}</p>
                      <p className="text-xs text-muted-foreground mt-0.5">{desc}</p>
                    </div>
                  </div>
                  <div className="flex gap-2 mt-3 justify-end">
                    <Button size="sm" variant="outline" onClick={() => generateDocument(id)}>
                      <Printer className="h-3.5 w-3.5 mr-1" /> Print
                    </Button>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      ))}
    </div>
  );
}
